### PR TITLE
Add lost coding conventions

### LINKED ISSUE #208: Coding conventions are missing
The coding conventions referenced from the contribution guidelines link to the old `xpcc-doc` repo, which we replaced with the `xpcc.io` repo (which doesn't contain the conventions either, lol).

Here is the last known version of the conventions:
https://gist.github.com/salkinium/3dba5ef2570a22ba76c748ee0c8243ad

### PR DESCRIPTION
**Pull request by salkinium**
Adds back the coding conventions (fixes #208).

~~Adds documentation to deprecate the DFG in favor of the one in [modm-devices](https://github.com/modm-io/modm-devices).~~
~~Adds all available device files to avoid future manual device file porting (relates to #221).~~
Moved to #226.

### CODE REVIEW

**Comment by strongly-typed** [comment]
Could you please also add STM32Lxx device files? You [added one here ](https://github.com/salkinium/xpcc/commit/47949a8fd0e734356a3c220674119ba1a50f5216) for my greatest pleasure. I just [resurrected this branch](https://github.com/strongly-typed/xpcc/commits/feature/stm32l4_support_2017) (and stripped the hwut) because will be discussing using STM32L476 with xpcc tomorrow with my team (after being disappointed multiple times by ST Cube HELL).

**Comment by salkinium** [comment]
> Could you please also add STM32Lxx device files?

Not in this PR. There are a number of things that need to be added and modified, so I'd like to see your branch as a separate PR.

Keep in mind, that the DFG in this repo generates inaccurate device files, since the package id is missing. This is ok, as long as you double check the device file for your specific device. The modm DFG has been rewritten from scratch to prevent these issues from the start. Unfortunately the device file format isn't backwards compatible.

**Comment by strongly-typed** [comment]
> so I'd like to see your branch as a separate PR.

Is it already worth a PR? Only some GPIOs and UART are tested, but not much more.

**Comment by salkinium** [comment]
Hm, then let's make a PR with just the lower part of that branch.

**Comment by salkinium** [comment]
Note that there are a few devices missing from this, in particular: F413, F423, F722, F723, F732, F733. This is because the device header files and some meta information have not been updated yet and the DFG depends on that.

**Comment by salkinium** [comment]
I'm changing this PR to only deal with the coding convention. I'll add more substantial changes to how we deal with device files and device headers in #226.

**Comment by salkinium** [comment]
Any objections for merging this?

**Pull request merged**
