### PR TITLE
[examples] Rename STM32F7 Discovery to STM32F746G.

### PR DESCRIPTION
**Pull request by strongly-typed**
As there are more than one STM32F7 Discovery Boards available.

### CODE REVIEW

**Comment by salkinium** [comment]
The CI job for the F769G examples builds everything, instead of just these projects.

**Comment by salkinium** [comment]
Note to self: These are the two F7 disco boards:
- [STM32F769I Discovery](http://www.st.com/content/st_com/en/products/evaluation-tools/product-evaluation-tools/mcu-eval-tools/stm32-mcu-eval-tools/stm32-mcu-discovery-kits/32f769idiscovery.html)
- [STM32F746G Discovery](http://www.st.com/content/st_com/en/products/evaluation-tools/product-evaluation-tools/mcu-eval-tools/stm32-mcu-eval-tools/stm32-mcu-discovery-kits/32f746gdiscovery.html)

**Comment by salkinium** [comment]
Hm. @strongly-typed `STM32F769G`? Are you sure?

**Comment by salkinium** [comment]
Ah, I see. You moved the folder to `stm32f746g_discovery`, but pointed the CI to `stm32f769g_discovery`. That won't work.

**Comment by strongly-typed** [comment]
Got confused, too. And another force-push ...

I will soon add some code for the STM32F769G because that M7 has a double precision FPU which will be used for some filtering.

**Pull request merged**
