### PR TITLE
Examples: Adopt SDL include path to <SDL.h>.

### PR DESCRIPTION
**Pull request by strongly-typed**
Because pkg-config —-cflags SDL includes SDL in path.

$ pkg-config --cflags sdl
-D_GNU_SOURCE=1 -D_THREAD_SAFE -I/usr/local/include/SDL

### CODE REVIEW

**Comment by strongly-typed** [comment]
Is SDL missing on the Travis CI? Probably not because checks ran before without problems?

What is the result of 
`pkg-config --libs --cflags gtkmm-2.4 cairomm-1.0 sdl`
on Travis CI?

On OS X 10.11.3 with gtkmm, cairomm and sdl installed with brew the result is
`-D_REENTRANT -D_GNU_SOURCE=1 -D_THREAD_SAFE -I/usr/local/Cellar/gtkmm/2.24.4_2/include/gtkmm-2.4 -I/usr/local/Cellar/gtkmm/2.24.4_2/lib/gtkmm-2.4/include -I/usr/local/Cellar/atkmm/2.24.2/include/atkmm-1.6 -I/usr/local/Cellar/gtk+/2.24.29/include/gtk-unix-print-2.0 -I/usr/local/Cellar/gtk+/2.24.29/include/gtk-2.0 -I/usr/local/Cellar/gtkmm/2.24.4_2/include/gdkmm-2.4 -I/usr/local/Cellar/gtkmm/2.24.4_2/lib/gdkmm-2.4/include -I/usr/local/Cellar/glibmm/2.46.3/include/giomm-2.4 -I/usr/local/Cellar/glibmm/2.46.3/lib/giomm-2.4/include -I/usr/local/Cellar/pangomm/2.38.1/include/pangomm-1.4 -I/usr/local/Cellar/pangomm/2.38.1/lib/pangomm-1.4/include -I/usr/local/Cellar/glibmm/2.46.3/include/glibmm-2.4 -I/usr/local/Cellar/glibmm/2.46.3/lib/glibmm-2.4/include -I/usr/local/Cellar/gtk+/2.24.29/include/gtk-2.0 -I/usr/local/Cellar/gtk+/2.24.29/lib/gtk-2.0/include -I/usr/local/Cellar/pango/1.38.1/include/pango-1.0 -I/usr/local/Cellar/harfbuzz/1.1.3/include/harfbuzz -I/usr/local/Cellar/pango/1.38.1/include/pango-1.0 -I/usr/local/Cellar/atk/2.18.0_1/include/atk-1.0 -I/usr/local/Cellar/gdk-pixbuf/2.32.3/include/gdk-pixbuf-2.0 -I/usr/local/Cellar/libpng/1.6.21/include/libpng16 -I/usr/local/Cellar/cairomm/1.12.0/include/cairomm-1.0 -I/usr/local/Cellar/cairomm/1.12.0/lib/cairomm-1.0/include -I/usr/local/Cellar/cairo/1.14.6/include/cairo -I/usr/local/Cellar/glib/2.46.2/include/glib-2.0 -I/usr/local/Cellar/glib/2.46.2/lib/glib-2.0/include -I/usr/local/opt/gettext/include -I/usr/local/Cellar/pixman/0.32.8/include/pixman-1 -I/usr/local/Cellar/fontconfig/2.11.1_1/include -I/usr/local/Cellar/freetype/2.6.2/include/freetype2 -I/usr/local/Cellar/libpng/1.6.21/include/libpng16 -I/usr/local/Cellar/libsigc++/2.6.2/include/sigc++-2.0 -I/usr/local/Cellar/libsigc++/2.6.2/lib/sigc++-2.0/include -I/usr/local/include/SDL -L/usr/local/Cellar/gtkmm/2.24.4_2/lib -L/usr/local/Cellar/atkmm/2.24.2/lib -L/usr/local/Cellar/gtk+/2.24.29/lib -L/usr/local/Cellar/gtkmm/2.24.4_2/lib -L/usr/local/Cellar/glibmm/2.46.3/lib -L/usr/local/Cellar/pangomm/2.38.1/lib -L/usr/local/Cellar/glibmm/2.46.3/lib -L/usr/local/Cellar/gtk+/2.24.29/lib -L/usr/local/Cellar/pango/1.38.1/lib -L/usr/local/Cellar/atk/2.18.0_1/lib -L/usr/local/Cellar/gdk-pixbuf/2.32.3/lib -L/usr/local/Cellar/glib/2.46.2/lib -L/usr/local/opt/gettext/lib -L/usr/local/Cellar/cairomm/1.12.0/lib -L/usr/local/Cellar/cairo/1.14.6/lib -L/usr/local/Cellar/libsigc++/2.6.2/lib -L/usr/local/lib -lgtkmm-2.4 -latkmm-1.6 -lgtk-quartz-2.0 -lgdkmm-2.4 -lgiomm-2.4 -lpangomm-1.4 -lglibmm-2.4 -lgtk-quartz-2.0 -lgdk-quartz-2.0 -lpangocairo-1.0 -lpango-1.0 -latk-1.0 -lgdk_pixbuf-2.0 -lgio-2.0 -lgobject-2.0 -lglib-2.0 -lintl -lcairomm-1.0 -lcairo -lsigc-2.0 -lSDLmain -lSDL -Wl,-framework,Cocoa`
all including the SDL in the path

**Comment by ekiwi** [comment]
With Fedora I get:

```
> pkg-config --libs --cflags sdl
-D_GNU_SOURCE=1 -D_REENTRANT -I/usr/include/SDL -lSDL -lpthread 
```

**Comment by ekiwi** [comment]
@strongly-typed: you can push commits to your pull request branch and Travis will try to build them. Before merging the request you can remove any debug/test commits.
This way you can try to resolve the problem with your original commit.

**Comment by strongly-typed** [comment]
@ekiwi Thanks for this test.
You get
`-I/usr/include/SDL`
as the include path for SDL which is the same on OS X. 

So any usage of `SDL.h` should not include `SDL/`, compare any example of SDL [1]

Apparently,

```
 check: examples/linux/build_info -> FAIL!
 check: examples/linux/can_debugger -> FAIL!
 check: examples/linux/communication/basic -> FAIL!
 check: examples/linux/git -> FAIL!
 check: examples/linux/gui/basic -> Ok
 check: examples/linux/logger -> FAIL!
 check: examples/linux/serial_interface -> FAIL!
 check: examples/linux/threads -> FAIL!`
```

any examples **except** the SDL example fail when correcting the include path. 

So the problem is that before this fix the global include path `/usr/include` was used in conjunction with `/SDL` to find `SDL.h` which is not the expected way of adding include paths.

I will try to figure out what is happening.

[1] https://wiki.libsdl.org/SDL_CreateWindow

**Comment by ekiwi** [comment]
> any examples except the SDL example fail when correcting the include path.

this probably means, that some hosted files include  `sdl_display.hpp
`even though they do not need it.

**Comment by salkinium** [comment]
This change works for me on OSX 10.9 with Apple LLVM version 6.0 (Clang v3.5).
However, it does give me a lot of warnings about unused linker input, because it passes all the flags from above into clang.

```
clang: warning: -lgtkmm-2.4: 'linker' input unused
clang: warning: -latkmm-1.6: 'linker' input unused
[...]
clang: warning: -lSDLmain: 'linker' input unused
clang: warning: -lSDL: 'linker' input unused
clang: warning: -Wl,-framework,Cocoa: 'linker' input unused
clang: warning: argument unused during compilation: '-L/usr/local/Cellar/gtkmm/2.24.4_2/lib'
clang: warning: argument unused during compilation: '-L/usr/local/Cellar/atkmm/2.24.2/lib'
[...]
clang: warning: argument unused during compilation: '-L/usr/local/Cellar/cairo/1.14.6/lib'
clang: warning: argument unused during compilation: '-L/usr/local/Cellar/libsigc++/2.6.2/lib'
clang: warning: argument unused during compilation: '-L/usr/local/lib'
```

Did you compile this using g++?

**Comment by salkinium** [comment]
Closing this, since the changes are not passing the CI.

**Comment by strongly-typed** [comment]
They are not passing CI because for hosted, display and SDL is part of the
"platform" and so SDL shall always be included (like boost), not only for
examples actually using the display.

The #include "SDL/SDL.h" is wrong, because it assumes that SDL is installed
in the global include path (like /usr/include/SDL), but it will fail when
someone installs SDL to (/usr/mylocalincludes/SDL)

**Comment by salkinium** [comment]
> The #include "SDL/SDL.h" is wrong, because it assumes that SDL is installed
> in the global include path (like /usr/include/SDL), but it will fail when
> someone installs SDL to (/usr/mylocalincludes/SDL)

Sure, I get that, but merging a change that breaks the CI is even more wrong.

> They are not passing CI because for hosted, display and SDL is part of the
> "platform" and so SDL shall always be included (like boost), not only for
> examples actually using the display.

Then our Travis CI setup needs to be adapted.
Unfortunately that's really annoying to do.

**Comment by salkinium** [comment]
I'm reopening this to keep this visable in the PR tabs.

**Pull request closed without merging**
