### PR TITLE
Stricter checking of sign and printf format string.

### PR DESCRIPTION
**Pull request by strongly-typed**
Enabling errors on warnings may break robot code and should be tested against RCA’s code base before merging.

### CODE REVIEW

**Review by salkinium — CHANGES_REQUESTED** [review]
Thanks for the fixes! 
Can you move the scons tools modifying commits into just one separate commit. This makes it easier for me to test this against RCA code and also to port this to modm.

**Comment by salkinium** [comment]
In general, I don't think using PRI is the correct approach here, this is just fighting the tools.
The reference implementation is our printf implementation, which has a very well defined set of sizes.
We should internally "remap" or "size upgrade" the type identifiers for the hosted implementation of printf, instead of doing this unreadable monkey business.
But this may not prevent gcc from throwing warnings about the inttypes.

**Comment by strongly-typed** [comment]
Thanks Niklas, great to hear from you.

Rearranged the commits.

Yes, this is a bit of fighting tools. `PRId16` is not so common, but it is very strict. Most of the warnings/errors came from compiling for arm.

**Comment by salkinium** [comment]
> Enable strict checkts.

typo!1!!

**Review by salkinium — APPROVED** [review]
Thanks. I might cherry-pick the commits without the scons commit first, since this might fail some RCA code.

**Comment by strongly-typed** [comment]
I'm currently checking RCA code. Season is over now.
I checked `big`, `little` and `display` against this branch and did not see any issues.

I'm willing to fix these issues. The point of this commit is to avoid these kind of failures in all kind of new code, including modm.

**Comment by salkinium** [comment]
> I'm currently checking RCA code. Season is over now.
> I checked `big`, `little` and `display` against this branch and did not see any issues.

Ok, let's do it then.

**Pull request merged**
