### PR TITLE
fixed encoding errors in template.py

### PR DESCRIPTION
**Pull request by lmoesch**
As mentioned in #345 , I set encoding to utf-8 to io.open calls in template.py, so that xpcc compiles on Windows machines. 

I tested it on stm32f0/4/7 boards so far.

### CODE REVIEW

**Review by salkinium — DISMISSED** [review]
Thanks!

**Comment by salkinium** [comment]
What happened here? Why are all the commits from #351 here?

**Comment by lmoesch** [comment]
sorry, I pushed to the wrong branch! Removed the latest commits so it should be fine now :)

**Review by salkinium — APPROVED** [review]
Thanks!

**Pull request merged**
