### PR TITLE
Fix TempFileMungeWindows Python 3 compatibility.

### PR DESCRIPTION
**Pull request by Sh4rK**
See relevant change in SCons: https://github.com/SCons/scons/commit/f51b065a8e4c009d58038d96b27eb0a6f7fb4189

### CODE REVIEW

**Comment by salkinium** [comment]
Could you remove the whitespace changes? They are quite noisy.
We should probably have one commit were we strip all the whitespace, but I'm reluctant, since it would touch so many files and add quite a bit of size to the history. 🙁

**Comment by Sh4rK** [comment]
Done, although the `.editorconfig` file in the root dir clearly has `trim_trailing_whitespace = true` in it :)

Removing all trailing whitespace in one huge commit would be satisfying, but for the reason you mentioned, I actually think that getting rid of them "naturally" (like how this commit originally did) is the better option. I agree that it introduces a bit of noise, but diff tools can be configured to ignore these (for example you can append `?w=1` to the end of a github diff url to ignore whitespace).

**Review by salkinium — APPROVED** [review]
I can't test it (without unreasonable effort), so if it work for you that's good enough for me ;-P

**Comment by salkinium** [comment]
> I actually think that getting rid of them "naturally" (like how this commit originally did) is the better option. I agree that it introduces a bit of noise, but diff tools can be configured to ignore these

I'd like to keep the changes in xpcc as clean and minimum as possible so that I have less work applying these changes to modm. I already have so resolve dozens of merge conflicts manually each time, I don't need more ;-P

**Comment by Sh4rK** [comment]
If modm will eventually replace xpcc, then not doing anything about unneeded whitespace is probably the best option then.

Edit: And yes, it works for me :)

**Comment by salkinium** [comment]
Merged manually.

**Pull request closed without merging**
