### PR TITLE
[doc] Fix missing link to STM32F0 Discovery board

### PR DESCRIPTION
**Pull request by rleh**
image
Edit: https://github.com/roboterclubaachen/xpcc/pull/284#discussion_r135272357

### CODE REVIEW

**Review by strongly-typed — APPROVED** [review]
Blame me!

**Comment by salkinium** [comment]
LOL. This is what happens when the readme is so familiar you never look at it again.

**Comment by salkinium** [comment]
@strongly-typed Why didn‘t the CircleCI run?

**Comment by strongly-typed** [comment]
Maybe because "Build forked pull requests" was not set or I just merged too early.

**Pull request merged**
