### PR TITLE
Update STM32F4 header and device files

### PR DESCRIPTION
**Pull request by salkinium**
- Adds required header files from CubeF4v2.4
- Updates device file reader, merger and auxilary information
- Adds device files for all STM32F4 devices.

### CODE REVIEW

**Comment by ekiwi** [comment]
Do we really want to add device files for devices that we do not own and thus cannot verify the support?
Currently I look at the available device files to determine which controllers should work with `xpcc`, but if we add all F4 devices, that might not be true anymore.

**Comment by dergraaf** [comment]
Perhaps a good solution is to provide a table with an overview about what has been verified in Hardware and when.
Only adding devices we own is not usefull longterms, but adding too many devices with no one to support them is worse.

**Comment by salkinium** [comment]
We kinda have a table of devices with first-class support in the [Readme](https://github.com/roboterclubaachen/xpcc#hardware-support).
However, I will add an explicit file with more details about this.

It's a little late for not adding a massive amount of device file, as I've already added _all_ AVR AT90, ATtiny, ATmega and Xmega device files…
(We don't even have Xmega drivers for anything).

The reasoning for add device files for devices we haven't tested it yet was, that generating the device files is not trivial, so someone new who might have a device we do not own, has practically no chance of even starting off.
So even if the support isn't good, there is a larger chance for someone unfamiliar with xpcc to start contributing to it.
Also, I just bought the STM32F469-Disco and I expect most peripherals to be similar if not identical.

I want to extract the device file generator out of xpcc into it's own repo and base it on [NetworkX](http://networkx.github.io) and therefore improve the merging algorithm.
The current algorithm only really works on flat, attributed lists, which doesn't work anymore on something very connected like clock trees.

Let's not kid ourselves here: We work with CAP: Computer Assisted Porting.
We could, with the right tools, provide relatively stable support for all STM32F\* devices, with reasonably little work.
Most ports are island solutions where one person takes exactly one variation of one device and copy and pastes a bunch of code.
I have not seen anyone else take such an algorithmically assisted and complete approach to porting, because it's not trivial. 
This is really exciting!

**Comment by salkinium** [comment]
Well, the STM32F469 Disco just works out the box. So I'm fairly confident the others also work.
Except for the SystemClock, of course, that is being addressed by #39.

**Pull request merged**
