### PR TITLE
TravisCI: Update avr-gcc to v4.9.2.

### PR DESCRIPTION
**Pull request by salkinium**
This is the latest toolchain that Atmel delivers for avr-gcc :-(

### CODE REVIEW

**Comment by salkinium** [comment]
Requires deleting all Travis CI caches and building it from scratch. CI is therefore a tad slow.

**Comment by strongly-typed** [comment]
Is 4.9.2 really the newest version? I'm running 4.9.3 from [homebrew](https://github.com/osx-cross/homebrew-avr/blob/master/avr-gcc49.rb). It seems to me that also 6.2.0 [is available from homebrew](https://github.com/osx-cross/homebrew-avr/blob/master/avr-gcc.rb).

**Comment by salkinium** [comment]
4.9.2 is the latest _from Atmel_. The homebrew version is the gcc upstream, which is missing the patches from Atmel, and therefore won't compile some newer devices. :_(

**Comment by salkinium** [comment]
This has been superseded by v5.4.0 in Atmels [toolchain release 3.6.0](http://distribute.atmel.no/tools/opensource/Atmel-AVR-GNU-Toolchain/3.6.0/). However, I couldn't find a pre-compiled [download link on their linux page](http://www.atmel.com/tools/ATMELAVRTOOLCHAINFORLINUX.aspx). We'll probably have to compile and host it ourselves.

Expected download link is, but doesn't exist:
- http://www.atmel.com/images/avr8-gnu-toolchain-3.6.0.1734-linux.any.x86_64.tar.gz

**Comment by salkinium** [comment]
Note to self: Also update arm-none-eabi-gcc to 2017q2 release.

**Comment by salkinium** [comment]
Closed in favor of #259.

**Pull request closed without merging**
