### PR TITLE
Basic QtCreator Project Generation Support

### PR DESCRIPTION
**Pull request by ekiwi**
This PR adds basic support for generating [QtCreator Generic Projects](https://github.com/qtproject/qt-creator/tree/master/src/plugins/genericprojectmanager).

I tested this quickly with our internal robot project by adding/modifying the following lines to the `SConstruct` file:

```
env.Alias('qtcreator', env.QtCreatorProject(files))
env.Alias('all', ['build', 'qtcreator', 'size'])
```

Of course, this needs some work:
- we need to add the correct work around for the `detect.hpp` issues mentioned in #67
- I want to try and generate a `.creator.shared` file that contains the build commands, which would make it possible to invoke `scons` from the QtCreator GUI
- finally GDB integration through the bare metal plugin is missing

However, I think this is already useful and therefore would like to see the PR merged, even though there are some features that should be added later.

### CODE REVIEW

**Comment by daniel-k** [comment]
Works mostly but it doesn't inlcude `.hpp` files, so they don't appear inside QtCreator.

**Comment by ekiwi** [comment]
@daniel-k @salkinium this should now include headerfiles
Can you please review my last commit?

**Comment by salkinium** [comment]
This works for me, and I have to say this is pretty amazing.
Autocompletion! Even for `generated_platform`. Even for `Gpio::connect` functions.
This must be that future people have been talking about!

(The include files might want to be relative in the `.includes` file, otherwise you can't share the project files.)

**Comment by ekiwi** [comment]
> The include files might want to be relative in the .includes file, otherwise you can't share the project files.

you are not supposed to share the project .... autogeneration FTW!

**Pull request merged**
