### PR TITLE
Improve SystemClock implementation for STM32

### PR DESCRIPTION
**Pull request by salkinium**
In this feature I rewrote the SystemClock templates to take input from a clock tree description in the device file and generate the appropriate template classes.
### Summary
- [x] Rewrite and generalize `ClockControl` class
- [x] Implement generic Source class
- [x] Implement generic Sink class
- [x] Implement generic Simple PLL class
- [ ] Implement generic Complex PLL class
- [ ] Move STM32 clock tree parsing code from [here](https://github.com/salkinium/save-the-clocktrees) into device file generator
- [ ] Implement generic STM32 clock tree parsing to auto-generate the clock trees of all STM32 devices
### Details

There currently are three classes that can be generated:
- clock sources,
- clock sinks, and
- simple PLLs (`Output = Input * Multiplier / Divisor`).

All classes conform to the following naming scheme of static member variables and methods:

``` cpp
static const TypeId::TypeIdName Id;
static constexpr ClockName Name;
static constexpr uint32_t InputFrequency;
static constexpr uint32_t OutputFrequency;
static StartupError enable(const uint32_t waitCycles = 1500);
```

The `ClockName` is a substitute for a type system, which enforces the allowed clock inputs for any tree node at compile time using static asserts.
This makes it possible to check this without template specializations, and therefore make it possible to use the same class regardless of tree length without duplicate code.

The `ClockTree` class has been renamed to `ClockControl` and the following naming scheme is introduced:
- `static bool enable{{SourceName}}Clock(uint32_t waitCycles = 1500);` for clock sources
- `static bool enable{{SinkName}}Clock({{SinkName}}ClockSource src, uint32_t waitCycles = 1500);` for clock sinks
- `static bool enablePll(PllSource source, ..., uint32_t waitCycles = 1500);`, different for every PLL

Typical usage of the SystemClock:

``` cpp
using systemClock = SystemClock< Pll< ExternalCrystal<MHz8>, MHz24 > >;
StartupError error = systemClock::enable();
```

The following examples are from the STM32F100 clock tree, but similar properties can be found on other STM32 devices.
#### Sources

``` xml
<!-- High speed clocks -->
<source name="InternalClock" type="clock" location="internal" speed="high" fixed="8000000"/>
<source name="ExternalClock" type="clock" location="external" speed="high" min="1000000" max="24000000"/>
<source name="ExternalCrystal" type="crystal" location="external" speed="high" min="4000000" max="24000000"/>
<!-- Low speed clocks -->
<source name="LowSpeedInternalClock" type="clock" location="internal" speed="low" fixed="40000"/>
<source name="LowSpeedExternalClock" type="clock" location="external" speed="low" min="1" max="1000000"/>
<source name="LowSpeedExternalCrystal" type="crystal" location="external" speed="low" fixed="32768"/>
```

Internal clocks (`InternalClock`) have a fixed output frequency. 
External clocks (`ExternalCrystal<MHz8>`) can have a custom output frequency which is asserted by maximum and minimum frequencies.
#### Simple PLLs

``` xml
<pll name="Pll" multiplier="2:16" max="24000000">
  <input name="InternalClock" divisor="2"/>
  <input name="ExternalClock" divisor="1:16" min="1000000"/>
  <input name="ExternalCrystal" divisor="1:16" min="1000000"/>
</pll>
```

The `PllSource` is automatically chosen and configured using the `ClockName Name` variable of the clock tree input.
The PLL class can at the moment only compute the divisor and multiplier settings at compile time given an input clock tree and an output frequency.
If no valid configuration is found, a failed assertion is raised.
Again, minimum and maximum frequencies on input and output paths are asserted.
#### Sinks

``` xml
<sink name="RealTimeClock">
  <input name="ExternalClock" divisor="128"/>
  <input name="ExternalCrystal" divisor="128"/>
  <input name="LowSpeedExternalClock"/>
  <input name="LowSpeedExternalCrystal"/>
  <input name="LowSpeedInternalClock"/>
  <output name="Rtc"/>
</sink>
```

Sinks receive a valid input node and generate the appropriate output frequency.
`output` elements are aliased to `OutputFrequency` with the appropriate prescaler if necessary, especially when traversing the sink tree downwards to the output leaves.

``` xml
<sink name="SystemClock" max="24000000">
  <input name="InternalClock"/>
  <input name="ExternalClock"/>
  <input name="ExternalCrystal"/>
  <input name="Pll"/>
  <tree name="Ahb" divisor="1,2,4,8,16,64,128,256,512" max="12000000">
    <output name="Hclk"/>
    <output name="SystemTimer"/>
    <output name="Fclk" alias="Fcpu"/>
    <!-- APB1 Prescaler -->
    <tree name="Apb1" divisor="1,2,4,8,16">
      <output name="Usart2"/>
      ...
      <output name="I2c2"/>
      <!-- if(APB1 prescaler == 1) x1 else x2 -->
      <tree name="Apb1Timer" depends="Apb1" multiplier="1,2,2,2,2">
        <output name="Timer2"/>
        ...
        <output name="Timer14"/>
      </tree>
    </tree>
    <!-- APB2 Prescaler -->
    <tree name="Apb2" divisor="1,2,4,8,16">
      <output name="Usart1"/>
      <output name="Spi1"/>
      <output name="Adc1"/>
      <!-- if(APB2 prescaler == 1) x1 else x2 -->
      <tree name="Apb2Timer" depends="Apb2" multiplier="1,2,2,2,2">
        <output name="Timer1"/>
        ...
        <output name="Timer17"/>
      </tree>
    </tree>
  </tree>
</sink>
```

### CODE REVIEW

**Comment by salkinium** [comment]
This is on hold until we can figure out how to generate the appropriate clock tree data and how to then use the clock tree data.

**Comment by salkinium** [comment]
I'm closing this, as there is no solution in sight for the near future.

**Comment by ekiwi** [comment]
> I'm closing this, as there is no solution in sight for the near future.

What's the problem?

Also I am in favor of leaving this pull request open, even if you stopped working on it, as it serves as a reminder, that we still need to fix our clock system.

**Comment by salkinium** [comment]
> What's the problem?
1. Mostly time. Also `ClockControl` has already been merged in #80 and together with #109 this isn't as pressing anymore. I would classify it as nice-to-have, but not mission critical.
2. There is also the annoyance that the PLL calculator code is [very, very unclear to write with C++11 constexpr](https://github.com/salkinium/xpcc/blob/feature/system_clock/src/xpcc/architecture/platform/driver/clock/stm32/plls.hpp.in#L151-L162) and would really benefit from using C++14 constexpr.
3. It's not clear to me how to collapse some of the "graph" properties of this clock "tree" into a few single templates. I mean, just from a language perspective, I'm unsure how to implement the many exceptions to the "tree" property of `SystemClock` in _one_ template class. Even with generated code.

> Also I am in favor of leaving this pull request open

Ok, but I'll likely not work on this for months.

**Comment by salkinium** [comment]
C++ compile time is the wrong vehicle for working on clock graphs. Further reading here: https://github.com/salkinium/save-the-clocktrees.

**Pull request closed without merging**
